# Generated by Django 5.1.4 on 2025-01-21 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('accepted', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.role')),
            ],
            options={
                'db_table': 'invitations',
                'indexes': [models.Index(fields=['email', 'organization'], name='invitations_email_053409_idx'), models.Index(fields=['expires_at'], name='invitations_expires_7f52c2_idx')],
            },
        ),
    ]
