# Generated by Django 5.1.4 on 2024-12-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
