# Generated by Django 5.1.4 on 2025-01-12 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_invitation_email_sent'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email', 'organization'], name='invitations_email_053409_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['expires_at'], name='invitations_expires_7f52c2_idx'),
        ),
    ]
