# Generated by Django 5.1.4 on 2025-01-06 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('contract_type', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('draft_completed', 'Draft Completed'), ('negotiation', 'Negotiation'), ('review', 'Review'), ('approval', 'Approval'), ('execution', 'Execution'), ('monitoring', 'Monitoring'), ('renewal', 'Renewal'), ('termination', 'Termination')], default='draft', max_length=50)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('is_renewable', models.BooleanField(default=False)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('terminated_at', models.DateField(blank=True, null=True)),
                ('terminated_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.URLField()),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=255)),
                ('party_type', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('isPrimary', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'counterparties',
            },
        ),
    ]
