# Generated by Django 5.1.5 on 2025-02-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('draft_completed', 'Draft Completed'), ('negotiation', 'Negotiation'), ('review', 'Review'), ('approval', 'Approval'), ('sign_pending', 'Sign Pending'), ('execution', 'Execution'), ('monitoring', 'Monitoring'), ('renewal', 'Renewal'), ('termination', 'Termination'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
    ]
