# Generated by Django 5.1.4 on 2025-01-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='renewed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
    ]
