# Generated by Django 5.1.4 on 2025-01-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_renewed_on_alter_contract_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file_path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
