# Generated by Django 5.1.4 on 2025-01-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('draft_completed', 'Draft Completed'), ('negotiation', 'Negotiation'), ('review', 'Review'), ('approval', 'Approval'), ('sign_pending', 'Sign Pending'), ('execution', 'Execution'), ('monitoring', 'Monitoring'), ('renewal', 'Renewal'), ('termination', 'Termination')], default='draft', max_length=50),
        ),
        migrations.DeleteModel(
            name='Counterparty',
        ),
    ]
