# Generated by Django 5.1.4 on 2025-01-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_file_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counterparty',
        ),
    ]
