# Generated by Django 5.1.4 on 2025-01-12 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_file_path'),
        ('contracts', '0004_alter_contract_file_path'),
    ]

    operations = [
    ]
