# Generated by Django 5.1.4 on 2025-01-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_merge_20250112_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file_path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
