# Generated by Django 5.1.4 on 2025-03-01 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureAPISenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending_verification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_api_sender_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signatureapi_sender_profiles',
            },
        ),
    ]
