# Generated by Django 5.1.4 on 2025-03-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esignature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatureapisenderprofile',
            name='status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='not_requested'),
        ),
    ]
