# Generated by Django 5.1.4 on 2025-03-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esignature', '0002_alter_signatureapisenderprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signatureapisenderprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='signatureapisenderprofile',
            name='api_sender_id',
            field=models.CharField(default=52, max_length=255),
            preserve_default=False,
        ),
    ]
