# Generated by Django 5.1.4 on 2025-02-05 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=255)),
                ('party_type', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('isPrimary', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='contracts.contract')),
            ],
            options={
                'db_table': 'counterparties',
            },
        ),
    ]
