# Generated by Django 5.1.4 on 2024-12-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_main_admin',
            field=models.BooleanField(default=False),
        ),
    ]
