# Generated by Django 5.1.4 on 2025-01-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_main_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_organization_admin',
        ),
    ]
